version: '3'

services:
  jenkins:
    container_name: jenkins
    build: ./jenkins
    ports:
      - '8080:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
  
  webapp:
    container_name: webapp
    build: ./webapp
    ports:
      - "80:80"

  web:
    image: php:7.2-apache
    container_name: htmlapplication
    ports:
      - "8000:80"
    volumes:
      - "./webapp:/var/www/html"

  git-server:
    build:
      dockerfile: gitserver.Dockerfile
      context: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./repos:/var/www/git

  sonarqube:
    image: sonarqube:latest
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    ports:
      - "9000:9000"
    networks:
      - reverse-proxy
    depends_on:
      - db
    volumes:
      - sonarqube_data:/opt/sonarqube/data

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - "postgresql:/var/lib/postgresql/data"
    networks:
      - reverse-proxy

  chrome:
    image: selenium/standalone-chrome:4.15.0-20231110
    ports:
      - "4444:4444"
    shm_size: 2gb

volumes:
  jenkins_data:
    driver: local
  postgresql:
  sonarqube_data:

networks:
  reverse-proxy:
    driver: bridge